name: Set up Conda environment
inputs:
  environment-file:
    description: Conda environment file to use.
    default: environment.yml
runs:
  using: composite
  steps:
    - name: Install ${{ inputs.environment-file }}
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ inputs.environment-file }}
        environment-name: test
        condarc-file: ci/condarc.yml
        cache-environment: true
        cache-downloads: true
