name: Run tests and report results
inputs:
  preload:
    description: Preload arguments for sanitizer
    required: false
  asan_options:
    description: Arguments for Address Sanitizer (ASAN)
    required: false
runs:
  using: composite
  steps:
    - name: Test
      run: ${{ inputs.asan_options }} ${{ inputs.preload }} ci/run_tests.sh
      shell: bash -el {0}

    - name: Publish test results
      uses: actions/upload-artifact@v3
      with:
        name: Test results
        path: test-data.xml
      if: failure()

    - name: Report Coverage
      run: coverage report -m
      shell: bash -el {0}
      if: failure()

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        name: codecov-pandas
        fail_ci_if_error: false
      if: failure()
